# POSTTEST 7

* Nama  : Ananta Yusra Putra Akmal 
* NIM   : 2109106024
* Kelas : A1 2021

* Dataset = Credit Risk

In [200]:
import tensorflow as tf

### Random Tensor

In [201]:
random_tensor = tf.random.normal([5,5], mean=2)
random_tensor.numpy()

array([[1.5735742 , 1.9511913 , 1.9638216 , 1.1887481 , 0.3123684 ],
       [1.2139575 , 2.6426644 , 0.963747  , 1.0621202 , 2.7395182 ],
       [2.5178688 , 1.6478394 , 1.6229796 , 1.3536284 , 1.4238756 ],
       [2.1892867 , 2.1826725 , 0.9898578 , 2.4929252 , 2.6479342 ],
       [0.85567963, 1.8886095 , 0.7567375 , 2.101771  , 1.1071188 ]],
      dtype=float32)

### Constan Tensor

In [202]:
# Shape 5 x 5 maka total bilangan = 25

prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97,101],shape=(5,5),dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

### Dimensi Tensor Random & Tensor Constan

In [203]:
print("Random  : ",random_tensor.shape)
print("Constan : ",prime_tensor.shape)

Random  :  (5, 5)
Constan :  (5, 5)


### Perhituangan Aritmatika Tensor Random & Tensor Constan

In [204]:
print("Penjumlahan :")
tf.add(random_tensor,prime_tensor).numpy()

Penjumlahan :


array([[  3.573574 ,   4.9511914,   6.9638214,   8.188748 ,  11.312368 ],
       [ 14.213958 ,  19.642664 ,  19.963747 ,  24.06212  ,  31.739517 ],
       [ 33.517868 ,  38.64784  ,  42.62298  ,  44.35363  ,  48.423874 ],
       [ 55.189285 ,  61.18267  ,  61.989857 ,  73.49293  ,  75.647934 ],
       [ 79.85568  ,  84.88861  ,  89.75674  ,  99.10177  , 102.10712  ]],
      dtype=float32)

In [205]:
print("Pengurangan :")
tf.subtract(random_tensor,prime_tensor).numpy()

Pengurangan :


array([[ -0.4264258,  -1.0488087,  -3.0361784,  -5.8112516, -10.687632 ],
       [-11.786042 , -14.357336 , -18.036253 , -21.93788  , -26.260483 ],
       [-28.482132 , -35.35216  , -39.37702  , -41.64637  , -45.576126 ],
       [-50.810715 , -56.81733  , -60.010143 , -68.50707  , -70.352066 ],
       [-78.14432  , -81.11139  , -88.24326  , -94.89823  , -99.89288  ]],
      dtype=float32)

In [206]:
print("Perkalian :")
tf.multiply(random_tensor,prime_tensor).numpy()

Perkalian :


array([[  3.1471484,   5.853574 ,   9.819108 ,   8.321237 ,   3.4360523],
       [ 15.781448 ,  44.925297 ,  18.311193 ,  24.428764 ,  79.44603  ],
       [ 78.05393  ,  60.97006  ,  66.54217  ,  58.20602  ,  66.92215  ],
       [116.032196 , 128.77768  ,  60.381325 , 176.99768  , 193.2992   ],
       [ 67.598694 , 156.7546   ,  67.34963  , 203.8718   , 111.819    ]],
      dtype=float32)

In [207]:
print("Pembagian :")
tf.divide(random_tensor,prime_tensor).numpy()

Pembagian :


array([[0.7867871 , 0.6503971 , 0.39276433, 0.16982116, 0.02839713],
       [0.09338135, 0.15545085, 0.05072353, 0.04617914, 0.09446614],
       [0.08122157, 0.0445362 , 0.03958487, 0.03147973, 0.03029522],
       [0.0413073 , 0.03699445, 0.01622718, 0.03511162, 0.03627307],
       [0.01083139, 0.02275433, 0.00850267, 0.02166774, 0.01096157]],
      dtype=float32)

In [208]:
print("Penjumlahan :")
tf.pow(random_tensor,prime_tensor).numpy()

Penjumlahan :


array([[2.4761357e+00, 7.4284730e+00, 2.9208565e+01, 3.3545086e+00,
        2.7627266e-06],
       [1.2434992e+01, 1.4952518e+07, 4.9579021e-01, 3.9993956e+00,
        4.9266457e+12],
       [2.7041186e+12, 1.0613312e+08, 4.1960045e+08, 4.5131175e+05,
        1.6337508e+07],
       [1.0865256e+18, 1.0007510e+20, 5.3695911e-01, 1.4667503e+28,
        7.4511750e+30],
       [4.4934959e-06, 8.3138206e+22, 1.6831633e-11, 1.9533752e+31,
        2.9081617e+04]], dtype=float32)

In [209]:
print("Perkalian + Penjumlahan :")

a = tf.multiply(prime_tensor,random_tensor) + tf.add(prime_tensor, random_tensor)
print(a)

Perkalian + Penjumlahan :
tf.Tensor(
[[  6.720722  10.804766  16.782928  16.509985  14.748421]
 [ 29.995407  64.56796   38.27494   48.490883 111.18555 ]
 [111.5718    99.6179   109.165146 102.55965  115.34602 ]
 [171.22148  189.96036  122.371185 250.4906   268.94714 ]
 [147.45438  241.6432   157.10637  302.97357  213.92612 ]], shape=(5, 5), dtype=float32)


### Nilai Max & Min Tensor Random

* Nilai Maximum

In [210]:
max = tf.argmax(random_tensor)
max.numpy()

array([2, 1, 0, 3, 1], dtype=int64)

In [211]:
max1 = tf.reduce_max(random_tensor)
max1.numpy()


2.7395182

* Nilai Minimum

In [212]:
min = tf.argmin(random_tensor)
min.numpy()

array([4, 2, 4, 1, 0], dtype=int64)

In [213]:
min1 = tf.reduce_min(random_tensor)
min1.numpy()

0.3123684

### Concatenation Tensor Random & Tensor Prime

In [214]:
concat = tf.concat([prime_tensor,random_tensor], axis=1)
concat.numpy()

array([[  2.        ,   3.        ,   5.        ,   7.        ,
         11.        ,   1.5735742 ,   1.9511913 ,   1.9638216 ,
          1.1887481 ,   0.3123684 ],
       [ 13.        ,  17.        ,  19.        ,  23.        ,
         29.        ,   1.2139575 ,   2.6426644 ,   0.963747  ,
          1.0621202 ,   2.7395182 ],
       [ 31.        ,  37.        ,  41.        ,  43.        ,
         47.        ,   2.5178688 ,   1.6478394 ,   1.6229796 ,
          1.3536284 ,   1.4238756 ],
       [ 53.        ,  59.        ,  61.        ,  71.        ,
         73.        ,   2.1892867 ,   2.1826725 ,   0.9898578 ,
          2.4929252 ,   2.6479342 ],
       [ 79.        ,  83.        ,  89.        ,  97.        ,
        101.        ,   0.85567963,   1.8886095 ,   0.7567375 ,
          2.101771  ,   1.1071188 ]], dtype=float32)

### Sorting Tensor Random & Tensor Prime Secara Descending

* Sorting Tensor Random

In [218]:
# Descending dari kanan ke kiri
random_sort = tf.sort(random_tensor, direction="DESCENDING")
random_sort.numpy()

array([[1.9638216 , 1.9511913 , 1.5735742 , 1.1887481 , 0.3123684 ],
       [2.7395182 , 2.6426644 , 1.2139575 , 1.0621202 , 0.963747  ],
       [2.5178688 , 1.6478394 , 1.6229796 , 1.4238756 , 1.3536284 ],
       [2.6479342 , 2.4929252 , 2.1892867 , 2.1826725 , 0.9898578 ],
       [2.101771  , 1.8886095 , 1.1071188 , 0.85567963, 0.7567375 ]],
      dtype=float32)

* Sorting Tensor Prime

In [216]:
# Descending dari atas ke bawah
prime_sort = tf.sort(prime_tensor, direction="DESCENDING")
prime_sort.numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)

* Sorting Concatenation (penggabungan)

In [217]:
sort = tf.sort(concat, direction="DESCENDING")
sort.numpy()

array([[ 11.        ,   7.        ,   5.        ,   3.        ,
          2.        ,   1.9638216 ,   1.9511913 ,   1.5735742 ,
          1.1887481 ,   0.3123684 ],
       [ 29.        ,  23.        ,  19.        ,  17.        ,
         13.        ,   2.7395182 ,   2.6426644 ,   1.2139575 ,
          1.0621202 ,   0.963747  ],
       [ 47.        ,  43.        ,  41.        ,  37.        ,
         31.        ,   2.5178688 ,   1.6478394 ,   1.6229796 ,
          1.4238756 ,   1.3536284 ],
       [ 73.        ,  71.        ,  61.        ,  59.        ,
         53.        ,   2.6479342 ,   2.4929252 ,   2.1892867 ,
          2.1826725 ,   0.9898578 ],
       [101.        ,  97.        ,  89.        ,  83.        ,
         79.        ,   2.101771  ,   1.8886095 ,   1.1071188 ,
          0.85567963,   0.7567375 ]], dtype=float32)