# POSTTEST 7

* Nama  : Ananta Yusra Putra Akmal 
* NIM   : 2109106024
* Kelas : A1 2021

* Dataset = Credit Risk

In [43]:
import tensorflow as tf

### Random Tensor

In [44]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.260854  ,  0.83830476, -1.1754787 ,  0.3226311 , -0.47526172],
       [-0.20888259,  0.20542455,  0.03153803,  1.0983171 ,  0.30674398],
       [ 0.26827812, -0.41831833,  0.5496434 ,  1.8365399 ,  0.5430508 ],
       [ 0.25515908, -0.4099539 , -0.7360904 ,  0.16072926,  0.5887899 ],
       [ 0.77006024,  1.0538839 , -2.321138  , -0.9837617 , -0.6619904 ]],
      dtype=float32)

### Constan Tensor

In [45]:
# Shape 5 x 5 maka total bilangan = 25

prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97,101],shape=(5,5),dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

### Dimensi Tensor Random & Tensor Constan

In [46]:
print("Random  : ",random_tensor.shape)
print("Constan : ",prime_tensor.shape)

Random  :  (5, 5)
Constan :  (5, 5)


### Perhituangan Aritmatika Tensor Random & Tensor Constan

In [47]:
print("Penjumlahan :")
tf.add(random_tensor,prime_tensor).numpy()

Penjumlahan :


array([[  1.739146 ,   3.8383048,   3.8245213,   7.322631 ,  10.524738 ],
       [ 12.791118 ,  17.205425 ,  19.031538 ,  24.098316 ,  29.306744 ],
       [ 31.268278 ,  36.58168  ,  41.549644 ,  44.83654  ,  47.543053 ],
       [ 53.255157 ,  58.590046 ,  60.26391  ,  71.16073  ,  73.58879  ],
       [ 79.77006  ,  84.05389  ,  86.67886  ,  96.016235 , 100.33801  ]],
      dtype=float32)

In [48]:
print("Pengurangan :")
tf.subtract(random_tensor,prime_tensor).numpy()

Pengurangan :


array([[  -2.260854 ,   -2.1616952,   -6.175479 ,   -6.677369 ,
         -11.475262 ],
       [ -13.208882 ,  -16.794575 ,  -18.968462 ,  -21.901684 ,
         -28.693256 ],
       [ -30.731722 ,  -37.41832  ,  -40.450356 ,  -41.16346  ,
         -46.456947 ],
       [ -52.744843 ,  -59.409954 ,  -61.73609  ,  -70.83927  ,
         -72.41121  ],
       [ -78.22994  ,  -81.94611  ,  -91.32114  ,  -97.983765 ,
        -101.66199  ]], dtype=float32)

In [49]:
print("Perkalian :")
tf.multiply(random_tensor,prime_tensor).numpy()

Perkalian :


array([[  -0.521708 ,    2.5149143,   -5.8773937,    2.2584176,
          -5.227879 ],
       [  -2.7154737,    3.4922173,    0.5992226,   25.261295 ,
           8.895576 ],
       [   8.316622 ,  -15.477778 ,   22.53538  ,   78.971214 ,
          25.523388 ],
       [  13.523431 ,  -24.187279 ,  -44.901516 ,   11.4117775,
          42.981663 ],
       [  60.83476  ,   87.47237  , -206.58127  ,  -95.42489  ,
         -66.86103  ]], dtype=float32)

In [50]:
print("Pembagian :")
tf.divide(random_tensor,prime_tensor).numpy()

Pembagian :


array([[-0.130427  ,  0.27943492, -0.23509574,  0.04609016, -0.04320561],
       [-0.01606789,  0.0120838 ,  0.0016599 ,  0.04775292,  0.01057738],
       [ 0.00865413, -0.0113059 ,  0.01340594,  0.04271023,  0.01155427],
       [ 0.00481432, -0.00694837, -0.01206706,  0.00226379,  0.00806561],
       [ 0.0097476 ,  0.0126974 , -0.0260802 , -0.01014187, -0.00655436]],
      dtype=float32)

In [51]:
print("Penjumlahan :")
tf.pow(random_tensor,prime_tensor).numpy()

Penjumlahan :


array([[ 6.8044811e-02,  5.8912277e-01, -2.2442634e+00,  3.6386770e-04,
        -2.7942235e-04],
       [-1.4412159e-09,  2.0658069e-12,  3.0050881e-29,  8.6444740e+00,
         1.3076917e-15],
       [ 1.9326045e-18, -9.9027350e-15,  2.2045586e-11,  2.2491347e+11,
         3.4474856e-13],
       [ 3.6390202e-32, -1.4169868e-23, -7.6348616e-09,  0.0000000e+00,
         1.6110337e-17],
       [ 1.0850540e-09,  7.7947151e+01, -3.5268258e+32, -2.0432547e-01,
        -8.0541759e-19]], dtype=float32)

In [52]:
print("Perkalian + Penjumlahan :")

a = tf.multiply(prime_tensor,random_tensor) + tf.add(prime_tensor, random_tensor)
print(a)

Perkalian + Penjumlahan :
tf.Tensor(
[[   1.217438      6.353219     -2.0528724     9.581049      5.2968593 ]
 [  10.075644     20.697643     19.63076      49.35961      38.20232   ]
 [  39.5849       21.1039       64.08502     123.807755     73.06644   ]
 [  66.77859      34.402767     15.362392     82.57251     116.57045   ]
 [ 140.60481     171.52625    -119.902405      0.59134674   33.476982  ]], shape=(5, 5), dtype=float32)


### Nilai Max & Min Tensor Random

* Nilai Maximum

In [55]:
max = tf.argmax(random_tensor)
max.numpy()

array([4, 4, 2, 2, 3], dtype=int64)

In [59]:
max1 = tf.reduce_max(random_tensor)
max1.numpy()


1.8365399

* Nilai Minimum

In [56]:
min = tf.argmin(random_tensor)
min.numpy()

array([0, 2, 4, 4, 4], dtype=int64)

In [61]:
min1 = tf.reduce_min(random_tensor)
min1.numpy()

-2.321138

### Concatenation Tensor Random & Tensor Prime

In [66]:
concat = tf.concat([prime_tensor,random_tensor], axis=1)
concat.numpy()

array([[ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01, -2.6085401e-01,  8.3830476e-01, -1.1754787e+00,
         3.2263109e-01, -4.7526172e-01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01, -2.0888259e-01,  2.0542455e-01,  3.1538032e-02,
         1.0983171e+00,  3.0674398e-01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01,  2.6827812e-01, -4.1831833e-01,  5.4964340e-01,
         1.8365399e+00,  5.4305083e-01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01,  2.5515908e-01, -4.0995389e-01, -7.3609042e-01,
         1.6072926e-01,  5.8878988e-01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0100000e+02,  7.7006024e-01,  1.0538839e+00, -2.3211379e+00,
        -9.8376173e-01, -6.6199040e-01]], dtype=float32)

### Sorting Tensor Random & Tensor Prime Secara Descending

In [68]:
sort = tf.sort(concat, direction="DESCENDING")
sort.numpy()

array([[ 1.1000000e+01,  7.0000000e+00,  5.0000000e+00,  3.0000000e+00,
         2.0000000e+00,  8.3830476e-01,  3.2263109e-01, -2.6085401e-01,
        -4.7526172e-01, -1.1754787e+00],
       [ 2.9000000e+01,  2.3000000e+01,  1.9000000e+01,  1.7000000e+01,
         1.3000000e+01,  1.0983171e+00,  3.0674398e-01,  2.0542455e-01,
         3.1538032e-02, -2.0888259e-01],
       [ 4.7000000e+01,  4.3000000e+01,  4.1000000e+01,  3.7000000e+01,
         3.1000000e+01,  1.8365399e+00,  5.4964340e-01,  5.4305083e-01,
         2.6827812e-01, -4.1831833e-01],
       [ 7.3000000e+01,  7.1000000e+01,  6.1000000e+01,  5.9000000e+01,
         5.3000000e+01,  5.8878988e-01,  2.5515908e-01,  1.6072926e-01,
        -4.0995389e-01, -7.3609042e-01],
       [ 1.0100000e+02,  9.7000000e+01,  8.9000000e+01,  8.3000000e+01,
         7.9000000e+01,  1.0538839e+00,  7.7006024e-01, -6.6199040e-01,
        -9.8376173e-01, -2.3211379e+00]], dtype=float32)