# POSTTEST 7

* Nama  : Ananta Yusra Putra Akmal 
* NIM   : 2109106024
* Kelas : A1 2021

* Dataset = Credit Risk

In [1]:
import tensorflow as tf

### Random Tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=2)
random_tensor.numpy()

array([[ 1.1669061 ,  2.8999763 ,  2.2311707 ,  0.8188387 ,  1.1998153 ],
       [ 2.0844169 ,  0.5037217 ,  4.3848433 ,  2.672774  ,  3.318078  ],
       [ 0.7592857 ,  3.9148016 ,  2.1064856 , -0.26909542,  2.069219  ],
       [ 3.5886583 ,  3.6001315 ,  2.369826  ,  0.21126986,  2.6921098 ],
       [ 1.9488378 ,  0.9112145 ,  2.521164  ,  0.8006438 ,  1.8151661 ]],
      dtype=float32)

### Constan Tensor

In [3]:
# Shape 5 x 5 maka total bilangan = 25

prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97,101],shape=(5,5),dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

### Dimensi Tensor Random & Tensor Constan

In [4]:
print("Random  : ",random_tensor.shape)
print("Constan : ",prime_tensor.shape)

Random  :  (5, 5)
Constan :  (5, 5)


### Perhituangan Aritmatika Tensor Random & Tensor Constan

In [5]:
print("Penjumlahan :")
tf.add(random_tensor,prime_tensor).numpy()

Penjumlahan :


array([[  3.166906 ,   5.8999763,   7.2311707,   7.8188386,  12.199816 ],
       [ 15.084417 ,  17.503721 ,  23.384844 ,  25.672773 ,  32.318077 ],
       [ 31.759285 ,  40.914803 ,  43.106487 ,  42.730904 ,  49.069218 ],
       [ 56.588657 ,  62.600132 ,  63.369827 ,  71.21127  ,  75.69211  ],
       [ 80.94884  ,  83.91122  ,  91.521164 ,  97.800644 , 102.81516  ]],
      dtype=float32)

In [6]:
print("Pengurangan :")
tf.subtract(random_tensor,prime_tensor).numpy()

Pengurangan :


array([[ -0.8330939 ,  -0.10002375,  -2.7688293 ,  -6.1811614 ,
         -9.800184  ],
       [-10.915583  , -16.496279  , -14.615156  , -20.327227  ,
        -25.681923  ],
       [-30.240715  , -33.085197  , -38.893513  , -43.269096  ,
        -44.930782  ],
       [-49.411343  , -55.399868  , -58.630173  , -70.78873   ,
        -70.30789   ],
       [-77.05116   , -82.08878   , -86.478836  , -96.199356  ,
        -99.18484   ]], dtype=float32)

In [7]:
print("Perkalian :")
tf.multiply(random_tensor,prime_tensor).numpy()

Perkalian :


array([[  2.3338122,   8.699928 ,  11.155853 ,   5.731871 ,  13.197968 ],
       [ 27.09742  ,   8.563269 ,  83.31203  ,  61.473804 ,  96.224266 ],
       [ 23.537857 , 144.84766  ,  86.36591  , -11.571103 ,  97.253296 ],
       [190.1989   , 212.40776  , 144.55939  ,  15.00016  , 196.52402  ],
       [153.95818  ,  75.6308   , 224.38359  ,  77.662445 , 183.33177  ]],
      dtype=float32)

In [8]:
print("Pembagian :")
tf.divide(random_tensor,prime_tensor).numpy()

Pembagian :


array([[ 0.58345306,  0.9666588 ,  0.44623414,  0.11697696,  0.10907412],
       [ 0.16033976,  0.02963069,  0.23078123,  0.11620757,  0.11441649],
       [ 0.02449309,  0.10580545,  0.0513777 , -0.00625803,  0.04402594],
       [ 0.06771053,  0.06101918,  0.03884961,  0.00297563,  0.03687822],
       [ 0.02466883,  0.01097849,  0.02832768,  0.00825406,  0.01797194]],
      dtype=float32)

In [9]:
print("Perkalian + Penjumlahan :")

a = tf.multiply(prime_tensor,random_tensor) + tf.add(prime_tensor, random_tensor)
print(a)

Perkalian + Penjumlahan :
tf.Tensor(
[[  5.500718  14.599905  18.387024  13.55071   25.397783]
 [ 42.18184   26.06699  106.69687   87.146576 128.54234 ]
 [ 55.297142 185.76245  129.4724    31.159801 146.32251 ]
 [246.78755  275.0079   207.92921   86.21143  272.21613 ]
 [234.90701  159.54202  315.90475  175.46309  286.14694 ]], shape=(5, 5), dtype=float32)


### Nilai Max & Min Tensor Random

* Nilai Maximum

In [10]:
max = tf.argmax(random_tensor)
max.numpy()

array([3, 2, 1, 1, 1], dtype=int64)

In [11]:
max1 = tf.reduce_max(random_tensor)
max1.numpy()


4.3848433

* Nilai Minimum

In [12]:
min = tf.argmin(random_tensor)
min.numpy()

array([2, 1, 2, 2, 0], dtype=int64)

In [13]:
min1 = tf.reduce_min(random_tensor)
min1.numpy()

-0.26909542

### Concatenation Tensor Random & Tensor Prime

In [14]:
concat = tf.concat([prime_tensor,random_tensor], axis=1)
concat.numpy()

array([[  2.        ,   3.        ,   5.        ,   7.        ,
         11.        ,   1.1669061 ,   2.8999763 ,   2.2311707 ,
          0.8188387 ,   1.1998153 ],
       [ 13.        ,  17.        ,  19.        ,  23.        ,
         29.        ,   2.0844169 ,   0.5037217 ,   4.3848433 ,
          2.672774  ,   3.318078  ],
       [ 31.        ,  37.        ,  41.        ,  43.        ,
         47.        ,   0.7592857 ,   3.9148016 ,   2.1064856 ,
         -0.26909542,   2.069219  ],
       [ 53.        ,  59.        ,  61.        ,  71.        ,
         73.        ,   3.5886583 ,   3.6001315 ,   2.369826  ,
          0.21126986,   2.6921098 ],
       [ 79.        ,  83.        ,  89.        ,  97.        ,
        101.        ,   1.9488378 ,   0.9112145 ,   2.521164  ,
          0.8006438 ,   1.8151661 ]], dtype=float32)

### Sorting Tensor Random & Tensor Prime Secara Descending

* Sorting Tensor Random

In [15]:
# Descending dari kanan ke kiri
random_sort = tf.sort(random_tensor, direction="DESCENDING")
random_sort.numpy()

array([[ 2.8999763 ,  2.2311707 ,  1.1998153 ,  1.1669061 ,  0.8188387 ],
       [ 4.3848433 ,  3.318078  ,  2.672774  ,  2.0844169 ,  0.5037217 ],
       [ 3.9148016 ,  2.1064856 ,  2.069219  ,  0.7592857 , -0.26909542],
       [ 3.6001315 ,  3.5886583 ,  2.6921098 ,  2.369826  ,  0.21126986],
       [ 2.521164  ,  1.9488378 ,  1.8151661 ,  0.9112145 ,  0.8006438 ]],
      dtype=float32)

* Sorting Tensor Prime

In [16]:
# Descending dari atas ke bawah
prime_sort = tf.sort(prime_tensor, direction="DESCENDING")
prime_sort.numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)

* Sorting Concatenation (penggabungan)

In [17]:
sort = tf.sort(concat, direction="DESCENDING")
sort.numpy()

array([[ 11.        ,   7.        ,   5.        ,   3.        ,
          2.8999763 ,   2.2311707 ,   2.        ,   1.1998153 ,
          1.1669061 ,   0.8188387 ],
       [ 29.        ,  23.        ,  19.        ,  17.        ,
         13.        ,   4.3848433 ,   3.318078  ,   2.672774  ,
          2.0844169 ,   0.5037217 ],
       [ 47.        ,  43.        ,  41.        ,  37.        ,
         31.        ,   3.9148016 ,   2.1064856 ,   2.069219  ,
          0.7592857 ,  -0.26909542],
       [ 73.        ,  71.        ,  61.        ,  59.        ,
         53.        ,   3.6001315 ,   3.5886583 ,   2.6921098 ,
          2.369826  ,   0.21126986],
       [101.        ,  97.        ,  89.        ,  83.        ,
         79.        ,   2.521164  ,   1.9488378 ,   1.8151661 ,
          0.9112145 ,   0.8006438 ]], dtype=float32)