# Modul 7 - TENSORFLOW

In [48]:
import tensorflow as tf

## Cara membuat Tensor 
## 1. Constant

### A. Constant

In [49]:
const_a = tf.constant([1,2,3,4], shape=[2,2], dtype=tf.float32)
const_a.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

### B. Zeros

In [50]:
zeros_b = tf.zeros(shape=[3,2], dtype=tf.int32)
zeros_b.numpy()

array([[0, 0],
       [0, 0],
       [0, 0]])

### C. Fill

In [51]:
fill_c = tf.fill ([4,4], 7)
fill_c.numpy()

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### D. Random

In [52]:
random_d = tf.random.normal([3,3])
random_d.numpy()

array([[ 0.26248357, -0.39992338, -1.6690489 ],
       [ 1.3026999 , -2.1235945 ,  0.75363535],
       [-0.6591549 ,  0.5271279 ,  2.220818  ]], dtype=float32)

In [53]:
random_d = tf.random.uniform([3,3])
random_d.numpy()

array([[0.6817477 , 0.12230277, 0.51105523],
       [0.18496406, 0.45736122, 0.00882399],
       [0.34741783, 0.38678765, 0.4506662 ]], dtype=float32)

### E. Convert To Tensor

In [54]:
tensor_e = tf.convert_to_tensor ([[1,3,5,7,9,11],[2,4,6,8,10,12]])
tensor_e.numpy()

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

## 2. Variabel

In [55]:
var1 = tf.Variable([[1,3,5,7],[2,4,6,8]])
#var1 = tf.Variable(tf.ones([3,3]))
var1

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 3, 5, 7],
       [2, 4, 6, 8]])>

In [56]:
# mengubah nilai var 1 di atas
var_1_ubah = [[1,2,3,4],[5,6,7,8]]
var1.assign(var_1_ubah)
var1.read_value()

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

# Tensor Slicing & Indexing

## 1. Slicing

In [57]:
tensor_i = tf.random.normal([4,3,3,3])
tensor_i

<tf.Tensor: shape=(4, 3, 3, 3), dtype=float32, numpy=
array([[[[-1.6671922 ,  1.7336985 ,  1.8079085 ],
         [-0.5410229 ,  1.8366683 , -1.3101039 ],
         [ 1.3095125 , -0.3021585 , -0.37006095]],

        [[-0.49199206,  2.0377698 ,  0.24396223],
         [-0.08175658, -0.11300121,  0.59010935],
         [ 0.11284916, -0.82850206, -0.87098914]],

        [[-0.43625554, -0.62202567,  1.6027342 ],
         [-0.82677513, -0.09687439, -0.02171415],
         [-1.8114176 ,  0.1006475 ,  0.20150732]]],


       [[[ 1.081875  , -0.44316837,  2.0324862 ],
         [-0.9336087 ,  0.11948035, -0.12837037],
         [ 2.47915   ,  1.0624591 , -0.18002874]],

        [[ 0.00777484, -0.41555348,  0.6091654 ],
         [-1.720893  ,  1.5952088 , -0.17038411],
         [ 0.8544632 ,  1.333876  , -0.6092174 ]],

        [[-1.0550654 ,  2.2909193 ,  2.266556  ],
         [-0.4026592 , -1.773901  ,  0.00546353],
         [-1.8190441 , -0.38776532, -1.3515956 ]]],


       [[[-0.708578  ,  1.6331

In [58]:
tensor_i[0,...]

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.6671922 ,  1.7336985 ,  1.8079085 ],
        [-0.5410229 ,  1.8366683 , -1.3101039 ],
        [ 1.3095125 , -0.3021585 , -0.37006095]],

       [[-0.49199206,  2.0377698 ,  0.24396223],
        [-0.08175658, -0.11300121,  0.59010935],
        [ 0.11284916, -0.82850206, -0.87098914]],

       [[-0.43625554, -0.62202567,  1.6027342 ],
        [-0.82677513, -0.09687439, -0.02171415],
        [-1.8114176 ,  0.1006475 ,  0.20150732]]], dtype=float32)>

In [59]:
tensor_i [::1,...]

<tf.Tensor: shape=(4, 3, 3, 3), dtype=float32, numpy=
array([[[[-1.6671922 ,  1.7336985 ,  1.8079085 ],
         [-0.5410229 ,  1.8366683 , -1.3101039 ],
         [ 1.3095125 , -0.3021585 , -0.37006095]],

        [[-0.49199206,  2.0377698 ,  0.24396223],
         [-0.08175658, -0.11300121,  0.59010935],
         [ 0.11284916, -0.82850206, -0.87098914]],

        [[-0.43625554, -0.62202567,  1.6027342 ],
         [-0.82677513, -0.09687439, -0.02171415],
         [-1.8114176 ,  0.1006475 ,  0.20150732]]],


       [[[ 1.081875  , -0.44316837,  2.0324862 ],
         [-0.9336087 ,  0.11948035, -0.12837037],
         [ 2.47915   ,  1.0624591 , -0.18002874]],

        [[ 0.00777484, -0.41555348,  0.6091654 ],
         [-1.720893  ,  1.5952088 , -0.17038411],
         [ 0.8544632 ,  1.333876  , -0.6092174 ]],

        [[-1.0550654 ,  2.2909193 ,  2.266556  ],
         [-0.4026592 , -1.773901  ,  0.00546353],
         [-1.8190441 , -0.38776532, -1.3515956 ]]],


       [[[-0.708578  ,  1.6331

In [60]:
tensor_i [::2,...]

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[-1.6671922 ,  1.7336985 ,  1.8079085 ],
         [-0.5410229 ,  1.8366683 , -1.3101039 ],
         [ 1.3095125 , -0.3021585 , -0.37006095]],

        [[-0.49199206,  2.0377698 ,  0.24396223],
         [-0.08175658, -0.11300121,  0.59010935],
         [ 0.11284916, -0.82850206, -0.87098914]],

        [[-0.43625554, -0.62202567,  1.6027342 ],
         [-0.82677513, -0.09687439, -0.02171415],
         [-1.8114176 ,  0.1006475 ,  0.20150732]]],


       [[[-0.708578  ,  1.6331673 ,  1.1470665 ],
         [-1.4808792 ,  0.4542845 ,  0.80947775],
         [-0.32380098, -1.4630258 , -0.5499172 ]],

        [[ 0.5353053 ,  1.0726521 ,  0.9851449 ],
         [-0.44089013, -0.45650128, -2.060307  ],
         [-0.4406397 , -0.715329  , -1.5631055 ]],

        [[-1.1593112 , -0.3529973 , -0.87977225],
         [ 1.5992174 , -1.2120845 ,  0.9312321 ],
         [ 0.7663284 , -0.7182771 , -0.6905023 ]]]], dtype=float32)>

## 2. indexing

### A. Gather

In [61]:
indices = [0,1,3]
tf.gather(tensor_i, axis=0, indices=indices)

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[-1.6671922 ,  1.7336985 ,  1.8079085 ],
         [-0.5410229 ,  1.8366683 , -1.3101039 ],
         [ 1.3095125 , -0.3021585 , -0.37006095]],

        [[-0.49199206,  2.0377698 ,  0.24396223],
         [-0.08175658, -0.11300121,  0.59010935],
         [ 0.11284916, -0.82850206, -0.87098914]],

        [[-0.43625554, -0.62202567,  1.6027342 ],
         [-0.82677513, -0.09687439, -0.02171415],
         [-1.8114176 ,  0.1006475 ,  0.20150732]]],


       [[[ 1.081875  , -0.44316837,  2.0324862 ],
         [-0.9336087 ,  0.11948035, -0.12837037],
         [ 2.47915   ,  1.0624591 , -0.18002874]],

        [[ 0.00777484, -0.41555348,  0.6091654 ],
         [-1.720893  ,  1.5952088 , -0.17038411],
         [ 0.8544632 ,  1.333876  , -0.6092174 ]],

        [[-1.0550654 ,  2.2909193 ,  2.266556  ],
         [-0.4026592 , -1.773901  ,  0.00546353],
         [-1.8190441 , -0.38776532, -1.3515956 ]]],


       [[[ 0.92149156,  1.4414

### B. Gather n-Dimension

In [62]:
indices2 = [[0,1,1,0], [1,2,2,0]]
tf.gather_nd(tensor_i, indices=indices2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.08175658, -1.8190441 ], dtype=float32)>

# Tensor Dimension Modificaton

## 1. Dimension Display

In [63]:
dim_display = tf.constant([[1,2,3,4]], shape=[2,2])
dim_display.shape

TensorShape([2, 2])

In [66]:
dim_display.get_shape

<bound method _EagerTensorBase.get_shape of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>>

In [67]:
tf.shape(dim_display)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2])>

## 2. Dimension Reshaping

In [68]:
dim_reshape = tf.constant([[1,2,3], [4,5,6]])
dim_reshape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [71]:
tf.reshape(dim_reshape, (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

## 3. Dimension Ekspansion (perbesaran)

In [73]:
dim_expand = tf.random.normal([100,100,3], seed=1)
dim_expand.shape

TensorShape([100, 100, 3])

In [76]:
tf.expand_dims(dim_expand, axis=0).shape

TensorShape([1, 100, 100, 3])

In [77]:
tf.expand_dims(dim_expand, axis=1).shape

TensorShape([100, 1, 100, 3])

## 4. Dimension Squeezing

In [78]:
dim_squeezing = tf.random.normal([100,1,100,3])

In [79]:
dim_squeezing2 = tf.squeeze(dim_squeezing)
dim_squeezing2.shape

TensorShape([100, 100, 3])

## 5. Transpose

In [80]:
trp = tf.constant([1,2,3,4,5,6], shape=[2,3])
trp.shape

TensorShape([2, 3])

In [81]:
trp2 = tf.transpose(trp)
trp2.shape

TensorShape([3, 2])

## 6. Brodcast

In [86]:
brd = tf.constant([1,2,3,4,5,6,7]) #panjang kolom =7
brd

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7])>

In [88]:
brd2 = tf.broadcast_to(brd, shape=[4,7]) #4,7 dimana 7=jumlah kolom dan harus sama dengan panjang kolom di atas
brd2

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])>

# Aritmatika Tensor

In [91]:
# PENJUMLAHAN

a = tf.constant([[3,5],[6,8]])
b = tf.constant([[1,6],[2,9]])

tf.add(a,b)
# a+b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 11],
       [ 8, 17]])>

In [92]:
# PERKALIAN

tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 13,  63],
       [ 22, 108]])>

In [95]:
# STATISTIKA

argmax = tf.constant([[3,5,1],[6,8,2], [7,5,9]])
argmax

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 5, 1],
       [6, 8, 2],
       [7, 5, 9]])>

In [96]:
max1 = tf.argmax(argmax, axis=0) # Untuk melihat lokasi nilai maksimum per kolom 
max1

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 1, 2], dtype=int64)>

In [97]:
max2 = tf.argmax(argmax, axis=1) # Untuk melihat lokasi nilai maksimum per baris
max2

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 2], dtype=int64)>

##  Tensor Concat

### A. Concat

In [100]:
concat1 = tf.random.uniform([4,10,10,3])
concat2 = tf.random.uniform([40,10,10,3])

In [101]:
concat1dan2 = tf.concat([concat1,concat2], axis=0)
concat1dan2

<tf.Tensor: shape=(44, 10, 10, 3), dtype=float32, numpy=
array([[[[0.19115114, 0.69179654, 0.6086279 ],
         [0.33507097, 0.6824186 , 0.35840917],
         [0.5263349 , 0.9207779 , 0.8837756 ],
         ...,
         [0.36701512, 0.7809378 , 0.18206549],
         [0.19923246, 0.41463494, 0.9282819 ],
         [0.12569845, 0.17568028, 0.860991  ]],

        [[0.33330595, 0.03989685, 0.39391935],
         [0.93434346, 0.852221  , 0.44219303],
         [0.0798043 , 0.88092875, 0.2968397 ],
         ...,
         [0.24932194, 0.7071072 , 0.88592243],
         [0.3937347 , 0.34775817, 0.9801091 ],
         [0.20033395, 0.4906733 , 0.77525496]],

        [[0.6138891 , 0.05534995, 0.1301328 ],
         [0.912691  , 0.8240535 , 0.5215043 ],
         [0.237602  , 0.7636355 , 0.8189169 ],
         ...,
         [0.540972  , 0.83089674, 0.6768333 ],
         [0.25220227, 0.6891748 , 0.7614118 ],
         [0.5693524 , 0.7347069 , 0.41501725]],

        ...,

        [[0.16589642, 0.7895671 , 0

### B. tf.stack()

In [104]:
stack1 = tf.random.normal([10,10,3])
stack2 = tf.random.normal([10,10,3])

In [105]:
stack1dan2 = tf.stack([stack1, stack2], axis=0)
stack1dan2

<tf.Tensor: shape=(2, 10, 10, 3), dtype=float32, numpy=
array([[[[-8.26406598e-01,  9.97401476e-01,  1.09323823e+00],
         [ 6.46544099e-01, -3.80137473e-01,  4.60822791e-01],
         [ 5.39992392e-01, -4.76069629e-01, -3.12253088e-01],
         [ 9.06706136e-03,  4.17022228e-01, -5.53502381e-01],
         [-3.79601598e-01, -9.72271860e-01, -3.82834584e-01],
         [ 1.23404956e+00, -1.40568972e+00,  8.49839032e-01],
         [-4.39174414e-01, -4.31503616e-02,  3.41842562e-01],
         [ 7.75657415e-01, -2.01280981e-01,  3.94437551e-01],
         [ 4.61318821e-01, -3.84277165e-01, -3.90469611e-01],
         [-2.13771895e-01, -1.96517909e+00,  1.55620646e+00]],

        [[ 1.15477610e+00,  2.08783284e-01,  1.46534216e+00],
         [-8.70964110e-01,  1.12494051e+00, -6.83848739e-01],
         [ 1.88020277e+00, -9.56325233e-02,  6.83454812e-01],
         [-1.08174884e+00, -1.06973577e+00,  5.24220347e-01],
         [ 2.91480327e+00, -1.02151299e+00,  1.94879613e-05],
         [-2

## Tensor Splitting

### A. tf.unstack()

In [107]:
unstack1dan2 = tf.unstack(stack1dan2)
unstack1dan2

[<tf.Tensor: shape=(10, 10, 3), dtype=float32, numpy=
 array([[[-8.26406598e-01,  9.97401476e-01,  1.09323823e+00],
         [ 6.46544099e-01, -3.80137473e-01,  4.60822791e-01],
         [ 5.39992392e-01, -4.76069629e-01, -3.12253088e-01],
         [ 9.06706136e-03,  4.17022228e-01, -5.53502381e-01],
         [-3.79601598e-01, -9.72271860e-01, -3.82834584e-01],
         [ 1.23404956e+00, -1.40568972e+00,  8.49839032e-01],
         [-4.39174414e-01, -4.31503616e-02,  3.41842562e-01],
         [ 7.75657415e-01, -2.01280981e-01,  3.94437551e-01],
         [ 4.61318821e-01, -3.84277165e-01, -3.90469611e-01],
         [-2.13771895e-01, -1.96517909e+00,  1.55620646e+00]],
 
        [[ 1.15477610e+00,  2.08783284e-01,  1.46534216e+00],
         [-8.70964110e-01,  1.12494051e+00, -6.83848739e-01],
         [ 1.88020277e+00, -9.56325233e-02,  6.83454812e-01],
         [-1.08174884e+00, -1.06973577e+00,  5.24220347e-01],
         [ 2.91480327e+00, -1.02151299e+00,  1.94879613e-05],
         [-2.

## Tensor Sorting

### tf.sort()

In [108]:
# TF.SORT

sort1 = tf.random.shuffle(tf.range(10))
sort1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([3, 4, 2, 6, 0, 1, 5, 8, 9, 7])>

In [109]:
sort_asc = tf.sort(sort1, direction="ASCENDING")
sort_asc

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [110]:
sort_desc = tf.sort(sort1, direction="DESCENDING")
sort_desc

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])>

In [111]:
# Menampilkan indexnya
argsort = tf.sort(sort1, direction="ASCENDING")
argsort

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

### tf.nn.top_k

In [112]:
# TF.NN.TOP_K

values, index = tf.nn.top_k(sort1, 5)
values.numpy()

array([9, 8, 7, 6, 5])

In [113]:
index.numpy()

array([8, 7, 9, 3, 6])